DROP ALL OBJECTS DELETE FILES;
-- DROP TABLE IF EXISTS study_class_grade_level;
-- DROP TABLE IF EXISTS study_class;
-- DROP TABLE IF EXISTS study_group_grade_level;
-- DROP TABLE IF EXISTS study_group;
-- DROP TABLE IF EXISTS student_subject;
-- DROP TABLE IF EXISTS subject;
-- DROP TABLE IF EXISTS student;
-- DROP TABLE IF EXISTS person;

CREATE TABLE IF NOT EXISTS person (
  id INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS student (
  id INT AUTO_INCREMENT PRIMARY KEY,
  grade_level INT NOT NULL DEFAULT 0,
  study_class INT DEFAULT NULL,
  study_group INT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS subject (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS study_class (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS study_group (
  id INT AUTO_INCREMENT PRIMARY KEY,
  min_students INT NOT NULL DEFAULT 0,
  max_students INT NOT NULL DEFAULT 100
);
